"""Static match metadata used to seed the IPL 2026 schedule."""

IPL_2026_MATCHES = [
    {
        "match_number": 1,
        "team_1": "SRH",
        "team_2": "RCB",
        "stadium": "M.Chinnaswamy Stadium",
        "date_played": "2026-03-28",
    },
    {
        "match_number": 2,
        "team_1": "KKR",
        "team_2": "MI",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-03-29",
    },
    {
        "match_number": 3,
        "team_1": "CSK",
        "team_2": "RR",
        "stadium": "Barsapara Cricket Stadium",
        "date_played": "2026-03-30",
    },
    {
        "match_number": 4,
        "team_1": "GT",
        "team_2": "PBKS",
        "stadium": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
        "date_played": "2026-03-31",
    },
    {
        "match_number": 5,
        "team_1": "LSG",
        "team_2": "DC",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-04-01",
    },
    {
        "match_number": 6,
        "team_1": "SRH",
        "team_2": "KKR",
        "stadium": "Eden Gardens",
        "date_played": "2026-04-02",
    },
    {
        "match_number": 7,
        "team_1": "CSK",
        "team_2": "PBKS",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-04-03",
    },
    {
        "match_number": 8,
        "team_1": "MI",
        "team_2": "DC",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-04-04",
    },
    {
        "match_number": 9,
        "team_1": "RR",
        "team_2": "GT",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-04-04",
    },
    {
        "match_number": 10,
        "team_1": "SRH",
        "team_2": "LSG",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-04-05",
    },
    {
        "match_number": 11,
        "team_1": "RCB",
        "team_2": "CSK",
        "stadium": "M.Chinnaswamy Stadium",
        "date_played": "2026-04-05",
    },
    {
        "match_number": 12,
        "team_1": "KKR",
        "team_2": "PBKS",
        "stadium": "Eden Gardens",
        "date_played": "2026-04-06",
    },
    {
        "match_number": 13,
        "team_1": "RR",
        "team_2": "MI",
        "stadium": "Barsapara Cricket Stadium",
        "date_played": "2026-04-07",
    },
    {
        "match_number": 14,
        "team_1": "GT",
        "team_2": "DC",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-04-08",
    },
    {
        "match_number": 15,
        "team_1": "KKR",
        "team_2": "LSG",
        "stadium": "Eden Gardens",
        "date_played": "2026-04-09",
    },
    {
        "match_number": 16,
        "team_1": "RCB",
        "team_2": "RR",
        "stadium": "Barsapara Cricket Stadium",
        "date_played": "2026-04-10",
    },
    {
        "match_number": 17,
        "team_1": "SRH",
        "team_2": "PBKS",
        "stadium": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
        "date_played": "2026-04-11",
    },
    {
        "match_number": 18,
        "team_1": "CSK",
        "team_2": "DC",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-04-11",
    },
    {
        "match_number": 19,
        "team_1": "LSG",
        "team_2": "GT",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-04-12",
    },
    {
        "match_number": 20,
        "team_1": "RCB",
        "team_2": "MI",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-04-12",
    },
    {
        "match_number": 21,
        "team_1": "SRH",
        "team_2": "RR",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-04-13",
    },
    {
        "match_number": 22,
        "team_1": "CSK",
        "team_2": "KKR",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-04-14",
    },
    {
        "match_number": 23,
        "team_1": "LSG",
        "team_2": "RCB",
        "stadium": "M.Chinnaswamy Stadium",
        "date_played": "2026-04-15",
    },
    {
        "match_number": 24,
        "team_1": "MI",
        "team_2": "PBKS",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-04-16",
    },
    {
        "match_number": 25,
        "team_1": "KKR",
        "team_2": "GT",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-04-17",
    },
    {
        "match_number": 26,
        "team_1": "RCB",
        "team_2": "DC",
        "stadium": "M.Chinnaswamy Stadium",
        "date_played": "2026-04-18",
    },
    {
        "match_number": 27,
        "team_1": "SRH",
        "team_2": "CSK",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-04-18",
    },
    {
        "match_number": 28,
        "team_1": "RR",
        "team_2": "KKR",
        "stadium": "Eden Gardens",
        "date_played": "2026-04-19",
    },
    {
        "match_number": 29,
        "team_1": "PBKS",
        "team_2": "LSG",
        "stadium": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
        "date_played": "2026-04-19",
    },
    {
        "match_number": 30,
        "team_1": "MI",
        "team_2": "GT",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-04-20",
    },
    {
        "match_number": 31,
        "team_1": "SRH",
        "team_2": "DC",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-04-21",
    },
    {
        "match_number": 32,
        "team_1": "LSG",
        "team_2": "RR",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-04-22",
    },
    {
        "match_number": 33,
        "team_1": "MI",
        "team_2": "CSK",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-04-23",
    },
    {
        "match_number": 34,
        "team_1": "RCB",
        "team_2": "GT",
        "stadium": "M.Chinnaswamy Stadium",
        "date_played": "2026-04-24",
    },
    {
        "match_number": 35,
        "team_1": "DC",
        "team_2": "PBKS",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-04-25",
    },
    {
        "match_number": 36,
        "team_1": "RR",
        "team_2": "SRH",
        "stadium": "Sawai Mansingh Stadium",
        "date_played": "2026-04-25",
    },
    {
        "match_number": 37,
        "team_1": "GT",
        "team_2": "CSK",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-04-26",
    },
    {
        "match_number": 38,
        "team_1": "LSG",
        "team_2": "KKR",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-04-26",
    },
    {
        "match_number": 39,
        "team_1": "DC",
        "team_2": "RCB",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-04-27",
    },
    {
        "match_number": 40,
        "team_1": "PBKS",
        "team_2": "RR",
        "stadium": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur",
        "date_played": "2026-04-28",
    },
    {
        "match_number": 41,
        "team_1": "MI",
        "team_2": "SRH",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-04-29",
    },
    {
        "match_number": 42,
        "team_1": "GT",
        "team_2": "RCB",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-04-30",
    },
    {
        "match_number": 43,
        "team_1": "RR",
        "team_2": "DC",
        "stadium": "Sawai Mansingh Stadium",
        "date_played": "2026-05-01",
    },
    {
        "match_number": 44,
        "team_1": "CSK",
        "team_2": "MI",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-05-02",
    },
    {
        "match_number": 45,
        "team_1": "SRH",
        "team_2": "KKR",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-05-03",
    },
    {
        "match_number": 46,
        "team_1": "GT",
        "team_2": "PBKS",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-05-03",
    },
    {
        "match_number": 47,
        "team_1": "MI",
        "team_2": "LSG",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-05-04",
    },
    {
        "match_number": 48,
        "team_1": "DC",
        "team_2": "CSK",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-05-05",
    },
    {
        "match_number": 49,
        "team_1": "SRH",
        "team_2": "PBKS",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-05-06",
    },
    {
        "match_number": 50,
        "team_1": "LSG",
        "team_2": "RCB",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-05-07",
    },
    {
        "match_number": 51,
        "team_1": "DC",
        "team_2": "KKR",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-05-08",
    },
    {
        "match_number": 52,
        "team_1": "RR",
        "team_2": "GT",
        "stadium": "Sawai Mansingh Stadium",
        "date_played": "2026-05-09",
    },
    {
        "match_number": 53,
        "team_1": "CSK",
        "team_2": "LSG",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-05-10",
    },
    {
        "match_number": 54,
        "team_1": "RCB",
        "team_2": "MI",
        "stadium": "Shaheed Veer Narayan Singh International Stadium",
        "date_played": "2026-05-10",
    },
    {
        "match_number": 55,
        "team_1": "PBKS",
        "team_2": "DC",
        "stadium": "Himachal Pradesh Cricket Association Stadium",
        "date_played": "2026-05-11",
    },
    {
        "match_number": 56,
        "team_1": "GT",
        "team_2": "SRH",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-05-12",
    },
    {
        "match_number": 57,
        "team_1": "RCB",
        "team_2": "KKR",
        "stadium": "Shaheed Veer Narayan Singh International Stadium",
        "date_played": "2026-05-13",
    },
    {
        "match_number": 58,
        "team_1": "PBKS",
        "team_2": "MI",
        "stadium": "Himachal Pradesh Cricket Association Stadium",
        "date_played": "2026-05-14",
    },
    {
        "match_number": 59,
        "team_1": "LSG",
        "team_2": "CSK",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-05-15",
    },
    {
        "match_number": 60,
        "team_1": "KKR",
        "team_2": "GT",
        "stadium": "Eden Gardens",
        "date_played": "2026-05-16",
    },
    {
        "match_number": 61,
        "team_1": "PBKS",
        "team_2": "RCB",
        "stadium": "Himachal Pradesh Cricket Association Stadium",
        "date_played": "2026-05-17",
    },
    {
        "match_number": 62,
        "team_1": "DC",
        "team_2": "RR",
        "stadium": "Arun Jaitley Stadium",
        "date_played": "2026-05-17",
    },
    {
        "match_number": 63,
        "team_1": "CSK",
        "team_2": "SRH",
        "stadium": "MA Chidambaram Stadium",
        "date_played": "2026-05-18",
    },
    {
        "match_number": 64,
        "team_1": "RR",
        "team_2": "LSG",
        "stadium": "Sawai Mansingh Stadium",
        "date_played": "2026-05-19",
    },
    {
        "match_number": 65,
        "team_1": "KKR",
        "team_2": "MI",
        "stadium": "Eden Gardens",
        "date_played": "2026-05-20",
    },
    {
        "match_number": 66,
        "team_1": "CSK",
        "team_2": "GT",
        "stadium": "Narendra Modi Stadium",
        "date_played": "2026-05-21",
    },
    {
        "match_number": 67,
        "team_1": "SRH",
        "team_2": "RCB",
        "stadium": "Rajiv Gandhi International Stadium",
        "date_played": "2026-05-22",
    },
    {
        "match_number": 68,
        "team_1": "LSG",
        "team_2": "PBKS",
        "stadium": "Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium",
        "date_played": "2026-05-23",
    },
    {
        "match_number": 69,
        "team_1": "MI",
        "team_2": "RR",
        "stadium": "Wankhede Stadium",
        "date_played": "2026-05-24",
    },
    {
        "match_number": 70,
        "team_1": "KKR",
        "team_2": "DC",
        "stadium": "Eden Gardens",
        "date_played": "2026-05-24",
    },
]
